// packages/sketch-react/src/platform-applet/components/image.tsx
import React, { useMemo } from 'react'
import { SketchAppletImage } from '../elements'
import { SketchElementChild, SketchElementProps } from '../../types'
import { useSketchElementRegister } from '../../common/hooks'

export interface InternalSketchAppletImageProps extends SketchElementProps{
    src?: string
    children?: SketchElementChild | SketchElementChild[]
}

export const InternalSketchAppletImage: React.FC<InternalSketchAppletImageProps> = (props) => {
  const { src = '', style, parent, children } = props

  const sketchAppletImage = useMemo(() => new SketchAppletImage(src, style), [src, style])

  useSketchElementRegister({ parent, target: sketchAppletImage })

  const childrenVNodes = React.Children.toArray(children).map((child: SketchElementChild) => {
    const { props: childProps } = child
    if (!React.isValidElement(child)) return null
    return React.cloneElement(child, { ...childProps, parent: sketchAppletImage })
  })

  return <>{childrenVNodes}</>
}

// packages/sketch-framework-vue/src/platform-applet/components/image.tsx
import { defineComponent, defineProps } from 'vue'
import { useAsyncComputed, useSketchElementRegister } from '../../common/hooks'
import { SketchElementProps } from '../../common/types'
import { SketchAppletImage } from '../elements'

export interface InternalSketchTextProps extends SketchElementProps {
  src?: string;
}

export const InternalSketchAppletImage = defineComponent({
  setup: () => {
    const props = defineProps<InternalSketchTextProps>()

    const { src = '', parent, style } = props

    const sketchAppletImage = useAsyncComputed(() => SketchAppletImage.create({ src, style }))

    useSketchElementRegister({ parent, target: sketchAppletImage })
  }
})
