// packages/sketch-react/src/common/components/view.tsx
import React, { useMemo } from 'react'
import { SketchView, StyleSheetCssProperties } from '@sketchjs/runtime'
import { SketchElementChild, SketchElementProps } from '../../types'
import { useSketchElementRegister } from '../hooks'

export interface InternalSketchViewProps extends SketchElementProps {
    style?: StyleSheetCssProperties
    children?: SketchElementChild | SketchElementChild[]
}

export const InternalSketchView: React.FC<InternalSketchViewProps> = (props) => {
  const { style, parent, children } = props

  const sketchView = useMemo(() => new SketchView(style), [style])

  useSketchElementRegister({ parent, target: sketchView })

  const childrenVNodes = React.Children.toArray(children).map((child: SketchElementChild) => {
    const { props: childProps } = child
    if (!React.isValidElement(child)) return null
    return React.cloneElement(child, { ...childProps, parent: sketchView })
  })

  return <>{childrenVNodes}</>
}

// packages/sketch-framework-vue/src/common/components/view.tsx
import { computed, defineComponent, defineProps } from 'vue'
import { SketchView } from '@sketchjs/runtime'
import { useSketchElementRegister } from '../hooks'
import { SketchElementProps } from '../types'

export type InternalSketchViewProps = SketchElementProps

export const InternalSketchView = defineComponent({
  name: 'SketchView',
  setup: () => {
    const props = defineProps<InternalSketchViewProps>()

    const { parent, style } = props

    const sketchView = computed(() => SketchView.create({ style }))

    useSketchElementRegister({ parent, target: sketchView })

    return () => <slot parent={sketchView} />
  }
})
