// packages/sketch-framework-vue/src/common/components/root.tsx

import { defineEmits, defineProps, defineExpose, ref, defineComponent } from 'vue'
import { SketchElement, SketchRoot } from '@sketchjs/runtime'
import { useInternalSketchRootCtxProvider } from '../hooks';
import { SketchElementProps, SketchHandler } from '../types'

export type InternalSketchRootProps = Omit<SketchElementProps, 'parent'>

export interface InternalSketchRootEmits {
  (event: 'ready'): void;
}


export const InternalSketchRoot = defineComponent({
  setup:()=>{
    const emit = defineEmits<InternalSketchRootEmits>()

    const props = defineProps<InternalSketchRootProps>()

    const sketchElementSetRef = ref<Set<SketchElement>>(new Set())

    const sketchRoot = ref<SketchRoot>()


    const initSketchRoot = async (canvasNode: HTMLCanvasElement, canvasCtx: CanvasRenderingContext2D) => {
      const {style} = props
      sketchRoot.value = await SketchRoot.create({ canvas: canvasNode, ctx: canvasCtx, style })
    }

    const renderSketch = () => {
      return sketchRoot.value?.render()
    }

    const sketchToDataURL = (type?: string, quality?: any) => {
      return sketchRoot.value?.toDataURL(type, quality) || ''
    }


    const registerSketchElement = (sketchElement: SketchElement) => {
      return sketchElementSetRef.value.add(sketchElement)
    }

    const unregisterSketchElement = (sketchElement: SketchElement) => {
      return sketchElementSetRef.value.delete(sketchElement)
    }

    const triggerSketchElementUpdate = () => {
      const sketchElements = Array.from(sketchElementSetRef.value)
      const isAllSketchElementMounted = sketchElements.every((sketchElement) => sketchElement.isMounted)
      if (!isAllSketchElementMounted || !sketchElements.length) return
      emit('ready')
    }

    defineExpose<SketchHandler>({
      sketchRoot,
      init: initSketchRoot,
      render: renderSketch,
      toDataURL: sketchToDataURL
    })

    useInternalSketchRootCtxProvider({
      registerSketchElement,
      unregisterSketchElement,
      triggerSketchElementUpdate
    })
    return ()=> <slot parent={sketchRoot}/>
  }
})

// packages/sketch-framework-react/src/common/components/root.tsx
import React, { useImperativeHandle, useRef, useState } from 'react'
import { SketchElement, SketchRoot, StyleSheetCssProperties } from '@sketchjs/runtime'
import noop from 'lodash-es/noop'
import { SketchElementChild, SketchHandler } from '../types'
import { InternalSketchRootCtx, InternalSketchRootCtxVal } from '../hooks'

export interface InternalSketchRootProps {
    style?: StyleSheetCssProperties
    children?: SketchElementChild | SketchElementChild[];
    onReady?: () => void;
}

export const InternalSketchRoot = React.forwardRef<SketchHandler, InternalSketchRootProps>((props, ref) => {
  const { style, children, onReady = noop } = props

  const [sketchRoot, setSketchRoot] = useState<SketchRoot>()

  const sketchElementSetRef = useRef(new Set<SketchElement>())

  const initSketchRoot = async (canvasNode: HTMLCanvasElement, canvasCtx: CanvasRenderingContext2D) => {
    const sketchRoot = await SketchRoot.create({ canvas: canvasNode, ctx: canvasCtx, style })
    setSketchRoot(sketchRoot)
  }

  const renderSketch = async () => {
    return sketchRoot?.render()
  }

  const sketchToDataURL = (type?: string, quality?: any) => {
    return sketchRoot?.toDataURL(type, quality) || ''
  }

  const registerSketchElement = (sketchElement: SketchElement) => {
    sketchElementSetRef.current.add(sketchElement)
  }

  const unregisterSketchElement = (sketchElement: SketchElement) => {
    sketchElementSetRef.current.delete(sketchElement)
  }

  const triggerSketchElementUpdate = () => {
    const sketchElements = Array.from(sketchElementSetRef.current)
    const isAllSketchElementMounted = sketchElements.every((sketchElement) => sketchElement.isMounted)
    if (!isAllSketchElementMounted || !sketchElements.length) return
    onReady()
  }

  useImperativeHandle(ref, () => ({
    sketchRoot,
    init: initSketchRoot,
    render: renderSketch,
    toDataURL: sketchToDataURL
  }))

  const childrenVNodes = React.Children.toArray(children).map((child: SketchElementChild) => {
    const { props: childProps } = child
    if (!React.isValidElement(child)) return null
    return React.cloneElement(child, { ...childProps, parent: sketchRoot })
  })

  const ctxVal:InternalSketchRootCtxVal = {
    registerSketchElement,
    unregisterSketchElement,
    triggerSketchElementUpdate
  }

  return (
    <InternalSketchRootCtx.Provider value={ctxVal}>
      {childrenVNodes}
    </InternalSketchRootCtx.Provider>
  )
})

InternalSketchRoot.displayName = 'SketchRoot'
