// packages/sketch-framework-vue/src/common/components/text.tsx
import { computed, defineComponent, PropType } from 'vue'
import { SketchElement, SketchText, StyleSheetCssProperties } from '@sketchjs/runtime'
import { useSketchElementRegister } from '../hooks'

export const SketchTextProps = {
  text: String,
  parent: Object as PropType<SketchElement>,
  style: Object as PropType<StyleSheetCssProperties>,
};

export const InternalSketchText = defineComponent({
  name: 'SketchText',
  props: SketchTextProps,
  setup: (props) => {

    const { text = '', parent, style } = props

    const sketchText = computed(() => SketchText.create({ text, style }))

    useSketchElementRegister({ parent, target: sketchText.value })

    return () => <slot/>
  }
})

// packages/sketch-framework-react/src/common/components/text.tsx
import React from 'react'
import { SketchElement, SketchText, StyleSheetCssProperties } from '@sketchjs/runtime'
import { useSketchElementRegister, useAsyncMemo } from '../hooks'

export interface InternalSketchTextProps {
    text?: string;
    parent?: SketchElement
    style?: StyleSheetCssProperties
}

export const InternalSketchText: React.FC<InternalSketchTextProps> = (props) => {
  const { text = '', style, parent } = props

  const sketchText = useAsyncMemo(() => SketchText.create({ text, style }), [text, style])

  useSketchElementRegister({ parent, target: sketchText })

  return null
}
