// packages/sketch-framework-vue/src/common/components/view.tsx
import { computed, defineComponent, defineProps } from 'vue'
import { SketchView } from '@sketchjs/runtime'
import { useSketchElementRegister } from '../hooks'
import { SketchElementProps } from '../types'

export type InternalSketchViewProps = SketchElementProps

export const InternalSketchView = defineComponent({
  name: 'SketchView',
  setup: () => {
    const props = defineProps<InternalSketchViewProps>()

    const { parent, style } = props

    const sketchView = computed(() => SketchView.create({ style }))

    useSketchElementRegister({ parent, target: sketchView })

    return () => <slot parent={sketchView} />
  }
})

// packages/sketch-framework-react/src/common/components/view.tsx
import React, { useMemo } from 'react'
import { SketchView } from '@sketchjs/runtime'
import { SketchElementProps } from '../types'
import { useSketchElement } from '../hooks'

export type InternalSketchViewProps = SketchElementProps;

export const InternalSketchView: React.FC<InternalSketchViewProps> = (props) => {
  const { style, parent, children } = props

  const sketchView = useMemo(() => SketchView.create({ style }), [style])

  const { childrenVNodes } = useSketchElement({ self: sketchView ,parent, children })

  return <>{childrenVNodes}</>
}
