// packages/sketch-framework-vue/src/platform-web/components/image.tsx
import { defineComponent, defineProps } from 'vue'
import { SketchImage } from '@sketchjs/runtime'
import { useAsyncComputed, useSketchElementRegister } from '../../common/hooks'
import { SketchElementProps } from '../../common/types'

export interface InternalSketchWebImageProps extends SketchElementProps {
  src?: string;
}

export const InternalSketchWebImage = defineComponent({
  name: 'SketchWebImage',
  setup: () => {
    const props = defineProps<InternalSketchWebImageProps>()

    const { src = '', parent, style } = props

    const sketchWebImage = useAsyncComputed(() => SketchImage.create({ src, style }))

    useSketchElementRegister({ parent, target: sketchWebImage })
  }
})

// packages/sketch-react/src/platform-web/components/image.tsx
import React, { useMemo } from 'react'
import { SketchImage } from '@sketchjs/runtime'
import { SketchElementChild, SketchElementProps } from '../../types'
import { useSketchElementRegister } from '../../common/hooks'

export interface InternalSketchWebImageProps extends SketchElementProps {
    src?: string
    children?: SketchElementChild | SketchElementChild[]
}

export const InternalSketchWebImage: React.FC<InternalSketchWebImageProps> = (props) => {
  const { src = '', style, parent, children } = props

  const sketchImage = useMemo(() => new SketchImage(src, style), [src, style])

  useSketchElementRegister({ parent, target: sketchImage })

  const childrenVNodes = React.Children.toArray(children).map((child: SketchElementChild) => {
    const { props: childProps } = child
    if (!React.isValidElement(child)) return null
    return React.cloneElement(child, { ...childProps, parent: sketchImage })
  })

  return <>{childrenVNodes}</>
}
